# Generated by Django 3.1.7 on 2021-04-11 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gallery',
            name='write_up',
        ),
        migrations.AlterField(
            model_name='gallery',
            name='images',
            field=models.FileField(blank=True, null=True, upload_to='media/'),
        ),
    ]
