# Generated by Django 3.1.7 on 2021-04-11 07:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20210411_1021'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='gallery',
            options={'verbose_name_plural': 'Gallery'},
        ),
        migrations.RemoveField(
            model_name='gallery',
            name='image',
        ),
        migrations.AlterField(
            model_name='gallery',
            name='title',
            field=models.CharField(default='breakfast', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='galleryimage',
            name='gallery',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='app.gallery'),
        ),
        migrations.AlterField(
            model_name='galleryimage',
            name='images',
            field=models.FileField(default='breakfast', upload_to='media/'),
            preserve_default=False,
        ),
    ]
