# Generated by Django 3.1.7 on 2021-04-11 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20210411_1030'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='galleryimage',
            options={},
        ),
        migrations.AddField(
            model_name='gallery',
            name='image',
            field=models.FileField(blank=True, upload_to=''),
        ),
    ]
