# Generated by Django 3.1.7 on 2021-04-12 14:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_auto_20210411_2144'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='services',
            name='title_description',
        ),
    ]
