# Generated by Django 3.1.7 on 2021-04-13 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_auto_20210413_1234'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deliveryfee',
            name='delivery_method',
        ),
        migrations.AddField(
            model_name='order',
            name='delivery_method',
            field=models.CharField(choices=[('self pickup', 'Self Pickup'), ('delivery', 'Delivery')], default='Delivery', max_length=100),
            preserve_default=False,
        ),
    ]
