# Generated by Django 3.1.7 on 2021-04-13 13:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_auto_20210413_1533'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DeliveryFee',
        ),
        migrations.RemoveField(
            model_name='order',
            name='delivery_fee',
        ),
        migrations.RemoveField(
            model_name='order',
            name='delivery_method',
        ),
    ]
